config/routes.rb
Rails.application.routes.draw do


  resources :games
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/add',  to: 'games#new'
  get '/randgame', to: 'static_pages#randgame'
  get '/about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class ScoreValidator < ActiveModel::Validator
  def validate(game)
    if game.w_score <= game.l_score
      game.errors[:base] << "Winner must score more than loser"
    end
    if game.l_score < 0
      game.errors[:base] << "Scores must be positive"
    end
  end
end

class Game < ApplicationRecord
    validates :winner, presence: true, length: {maximum: 30}
    validates :loser, presence: true, length: {maximum: 30}
    VALID_DATE_REGEX = /\A(((0)[0-9])|((1)[0-2]))(\/)([0-2][0-9]|(3)[0-1])(\/)\d{2}/
    validates :date, format: { with: VALID_DATE_REGEX}
    validates_with ScoreValidator

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
      render html: "hello, world!"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def standings
      @game = Game.all
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winner, :loser, :w_score, :l_score, :date)
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def add
  end

  def help
  end
  
  def randgame
      winner = [true, false].sample
      loser = (0..19).to_a.shuffle.first
      if winner
        @result = [21,loser]
      else
        @result = [loser,21]
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Ping Pong App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/standings_helper.rb
module StandingsHelper

    def standings
        full = Hash.new
        Game.all.each do |g|
        
            if not full.key? g.winner
              full[g.winner] = { "games" => 0, "wins" => 0, "pts" => 0 }
            end

            full[g.winner]["games"] += 1
            full[g.winner]["wins"]  += 1
            full[g.winner]["pts"]  += g.w_score
            
            if not full.key? g.loser
              full[g.loser] = { "games" => 0, "wins" => 0, "pts" => 0 }
            end
            full[g.loser]["games"]  += 1
            full[g.loser]["pts"]  += g.l_score
            
        end
        full.sort_by { |k, v| v["wins"].to_f / -v["games"] }
          
            
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :winner %>
    <%= form.text_field :winner, id: :game_winner %>
  </div>

  <div class="field">
    <%= form.label :loser %>
    <%= form.text_field :loser, id: :game_loser %>
  </div>

  <div class="field">
    <%= form.label :Winner_Score %>
    <%= form.number_field :w_score, id: :game_w_score %>
  </div>

  <div class="field">
    <%= form.label :Loser_Score %>
    <%= form.number_field :l_score, id: :game_l_score %>
  </div>

  <div class="field">
    <%= form.label :Date_MM_DD_YY %>
    <%= form.text_field :date, id: :game_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<!DOCTYPE html>
<html>
<style>
h1{text-align:center;}
th{font-size:25px;}
td{font-size:20px;}
</style>
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <col width="130">
  <col width="130">
  <col width="120">
  <col width="130">
  <thead>
    <tr>
      <th>Winner</th>
      <th>Loser</th>
      <th>Score</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.winner %></td>
        <td><%= game.loser %></td>
        <td><%= game.w_score.to_s + "-" + game.l_score.to_s %></td>
        <td><%= game.date %></td>
        <td><%= link_to 'Show', game %></td>
        <!--<td><%= link_to 'Edit', edit_game_path(game) %></td>  -->
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<!DOCTYPE html>
<html>
<style>
 .row {
  display: flex;
}

.column {
  flex: 33.33%;
  padding: 5px;
}
</style>

<h1>Add Game</h1>

<p>
    Add a game to be included in the standings
</p>
<div class="row">
  <div class="column">
    <%= render 'form', game: @game %>
  </div>
  <div class="column">
    <%= image_tag("ping-pong-sport.jpg", alt: "Paddles on Table", :size => "400x300") %>
  </div>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html>
<style>
h1{text-align:center;}
h2{text-align:center;
   font-size:30px;
}
p{text-align:center;}
</style>

<h1>Game Result</h1>
<h2> <%= @game.winner %> &emsp;<%= @game.w_score %><br/><br/><%= @game.loser %> &emsp;<%= @game.l_score %></h2>
<h2> Date:  <%= @game.date %> </h2>
<p><%= link_to 'Back', games_path %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    CSC 324 Individual Project</a>
    by Jared Booth</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Generate Random Game", randgame_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ping Pong App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "All Games", games_path %></li>
      <li><%= link_to "Add Game", add_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
 </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/
html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 
      
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track':
'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track':
'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
 </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1><%= yield(:title)%></h1>
<p>
   This site showcases my skill development in Ruby with the navifation throughout the site and the use of the MVC architecture. A header and foooter is included in the application layout, which keeps the code for them out of the seperate views. In addition, views are DRY with the use of a dynamic title function to remove unecessary code in the views. The home page, which shows the standings for all of the games added to the site best shows how I used the MVC architecture to create the site. In a seperate helper, each object of the Game model is organized using ruby to calculate the records of each player in the database. The view for the home page then references this organized data, and uses embedded ruby to display the results for each player.
</p>

app/views/static_pages/add.html.erb
<% provide(:title, "Add Game") %>
<h1><%= yield(:title)%></h1>
<p>
    Add a game to be included in the standings
</p>

app/views/static_pages/game.html.erb
<!DOCTYPE html>
<html>
<style>
h1{text-align:center;}
h2{text-align:center;
   font-size:30px;
}
p{text-align:center;}
</style>

<h1>Random Game Result</h1>
<h2> Player 1 &emsp;<%= @result[0] %><br/><br/>Player 2 &emsp;<%= @result[1] %></h2>
<p><%= link_to "Play again", game_path %></p>

</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<style>
h1{text-align:center;}
p{text-align:center;
   font-size:20px;
}
</style>

<% provide(:title, "Home") %>
  
  <h1><%= yield(:title)%></h1>
  <h2> Current Standings <h2>
   <table style="width:100%">
    <tr>
    <th>Name</th>
    <th>Win</th>
    <th>Loss</th>
    <th>Pct</th>
    <th>Pts/G</th>
    </tr>
    
    <% standings.each do |player| %>
        <tr>
          <td><%= player[0] %></td>
          <td><%= player[1]["wins"] %></td>
          <td><%= player[1]["games"] -  player[1]["wins"] %></td>
          <td><%= (player[1]["wins"].to_f / player[1]["games"]).round(3) %></td>
          <td><%= (player[1]["pts"].to_f / player[1]["games"]).round(1) %></td>
        </tr>
    <% end%>
  </table>
  

app/views/static_pages/randgame.html.erb
<!DOCTYPE html>
<html>
<style>
h1{text-align:center;}
h2{text-align:center;
   font-size:30px;
}
p{text-align:center;}
</style>

<h1>Random Game Result</h1>
<h2> Player 1 &emsp;<%= @result[0] %><br/><br/>Player 2 &emsp;<%= @result[1] %></h2>
<p><%= link_to "Play again", randgame_path %></p>

</html>